version: '3.8'
services:
  app:
    build:
      context: .
    container_name: ecommerce-laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:8.0
    container_name: ecommerce-laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce-laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ecommerce-laravel_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_data:
